### ISSUE TITLE
What's this extremely shady project?

### ISSUE THREAD

**Issue by Xerios** [aryamihirsingh/UnityPlugin#1]
Along with that unmanaged .dll, this seems way too suspicious...

**Comment by aryamihirs** [comment]
I'm sorry, what is shady about it?

**Comment by Xerios** [comment]
The fact that it loads up a .dll and there's literally no info on what that file does once loaded :+1:

**Comment by aryamihirs** [comment]
That is because I haven't really updated how the dll is being utilized. The purpose of me uploading it here was to provide the code to someone (its been just a days since I made this repo) . I will update and rewrite the documentation, properly explaining about how it works soon. :)
FYI the following link can be of great help: [http://www.alanzucconi.com/2015/10/11/how-to-write-native-plugins-for-unity/](url)
Cheers
